Fixes various problems with translate clearing search
helsingborg-stad/Municipio pull request #110
Opened 2020-09-02 13:17 UTC by jwinding

Fixes various problems with translate clearing search, using some js tricks/hacks.

Relies partly on the translate link in the footer-menu having the class 'translate-link-js', which one has to set in the admin pages.No longer updates any dist-files.

2020-09-02 13:48 UTC, nRamstedt requested changes

2020-09-02 13:48 UTC, nRamstedt commented on views/partials/archive-filters.blade.php
> +                const els = [ document.getElementById('filter-date-from'), document.getElementById('filter-date-to')];
Validate els exists

2020-09-02 13:48 UTC, nRamstedt commented on views/partials/archive-filters.blade.php
> +                function rewriteTranslateLink(){
Make sure it works with and without date-from filters

2021-12-06 13:28 UTC, closed without merging

2021-12-06 13:30 UTC, sebastianthulin commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/8e240406b0dd1187c6740c4b902ae672/pull-request/110)