3.0/feature/archive menus
helsingborg-stad/Municipio pull request #276
Opened 2022-03-09 10:43 UTC by sebastianthulin

Create a menu location in top of all pages-

2022-03-09 10:44 UTC, sebastianthulin commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/8e240406b0dd1187c6740c4b902ae672/pull-request/276)

2022-03-10 14:34 UTC, sebastianthulin commented
How to test: 

Add a new menu. 
Link it to an archive (multiple new menu positions should be generated, if not add a new post type)
Add links to the menu. Querystring only-links should be highlighted with primary color, if is current. 

A reset button should show if any querystring is set.

2022-03-10 21:39 UTC, ergr1001 approved these changes

2022-03-11 08:01 UTC, faejr requested changes
Looks good overall, but here's some suggestions :)

2022-03-11 09:46 UTC, merged