init
helsingborg-stad/Municipio pull request #394
Opened 2022-12-06 14:42 UTC by NiclasNorin

2022-12-08 14:55 UTC, sebastianthulin requested changes

2022-12-08 14:55 UTC, sebastianthulin commented on assets/source/3.0/sass/search.scss
> +    color: rgb(61, 61, 61);
Static colors not allowed. Please use any of the predefined var's. You may utilize one of the monotone vars.

2022-12-08 14:55 UTC, sebastianthulin commented on assets/source/3.0/sass/search.scss
>        width: 30%;
Repetative. Have you considerd using clamp function?

2022-12-08 14:55 UTC, sebastianthulin commented on views/v3/partials/search/hero-search-form.blade.php
> -    @group(['direction' => 'horizontal'])
Group where design to solove issues like these. If it's not working, you may redesign it.

2022-12-12 09:09 UTC, NiclasNorin commented on views/v3/partials/search/hero-search-form.blade.php
> -    @group(['direction' => 'horizontal'])
> Group where design to solove issues like these. If it's not working, you may redesign it.

I replaced the div with the group component. It made it possible to remove some of the styling. However the specific styling was still needed. I do not think we want to add more styling to the group component since it will make the usage too specific.

2022-12-21 13:57 UTC, merged