cu #865bgg6mw move innovation solutions into municipio
helsingborg-stad/Municipio pull request #419
Opened 2023-01-13 12:38 UTC by annalinneajohansson

2023-01-13 12:38 UTC, helsingborgsstad commented
Task linked: [CU-865bgg6mw Flytta Innovation-lösningar till Municipio](https://app.clickup.com/t/865bgg6mw)

2023-01-18 08:47 UTC, sebastianthulin requested changes

2023-01-18 08:47 UTC, sebastianthulin commented on library/Helper/WP.php
> +                fn ($p) => apply_filters('ProjectManagerIntegration/Helper/Municipio/mapPost', $p, $p->postType),
Filter needs to change namespace

2023-01-18 08:47 UTC, sebastianthulin commented on library/Helper/WP.php
> +                fn ($p) => apply_filters("ProjectManagerIntegration/Helper/Municipio/{$p->postType}/mapPost", $p),
Filter needs to change namespace

2023-01-18 12:20 UTC, sebastianthulin approved these changes

2023-01-18 12:20 UTC, merged