Allow administrator to publish unfiltered html
helsingborg-stad/Municipio pull request #421
Opened 2023-01-16 08:55 UTC by annalinneajohansson

2023-01-16 08:55 UTC, helsingborgsstad commented
Task linked: [CU-865bg0zbq HTML-tecken encodas i ACF fält.](https://app.clickup.com/t/865bg0zbq)

2023-01-18 08:11 UTC, sebastianthulin requested changes

2023-01-18 08:11 UTC, sebastianthulin commented on library/Admin/Roles/Editor.php
> +        $role = get_role('administrator');
Editor needs this capability too.

2023-01-18 12:11 UTC, sebastianthulin approved these changes

2023-01-18 12:11 UTC, merged