WIP Ajax sideload font files if they're missing
helsingborg-stad/Municipio pull request #437
Opened 2023-01-23 15:50 UTC by annalinneajohansson

2023-01-23 15:50 UTC, helsingborgsstad commented
Task linked: [CU-865bjjrx3 Custom fonts behöver hämtas och laddas upp i mediabiblioteket om de saknas](https://app.clickup.com/t/865bjjrx3)

2023-01-24 09:17 UTC, thorbrink commented on assets/source/3.0/js/admin/designShare.js
> +                                                .then(response => console.log(response))
```suggestion
```

2023-01-24 09:18 UTC, thorbrink requested changes
Only found a console.log leftover.

2023-01-24 09:25 UTC, thorbrink approved these changes
🥇

2023-01-24 09:30 UTC, merged