- feat(purpose): add PurposeCollection and PurposeComponent interfaces and implement in PurposeFactory, Event and Place classes - refactor(purpose): remove secondaryPurpose property and related methods - docs(purpose): update class and method docblocks in PurposeFactory, Event, and Place classes
helsingborg-stad/Municipio pull request #626
Opened 2023-06-19 13:38 UTC by annalinneajohansson

2023-06-19 13:38 UTC, helsingborgsstad commented
Task linked: [CU-865cdv0pq Refaktorering av purpose controllers enl. composition pattern](https://app.clickup.com/t/865cdv0pq)

2023-08-15 08:34 UTC, thorbrink requested changes
Beautiful 🥇 Just added a request for a file/class rename.

2023-08-15 08:34 UTC, thorbrink commented on library/Controller/ArchivePurpose.php
This file should probably be renamed to `ArchiveContentType`. Or perhaps both the class and the file should be renamed to something that indicated that this handles archive for places?

2023-08-17 07:34 UTC, annalinneajohansson commented on library/Controller/ArchivePurpose.php
It's meant to generally handle archives containing any kind of content type (not just places), the same way standard Archive.php does in WP so it should be ArchiveContentType

2023-08-24 12:55 UTC, merged