Feat: Subitems under nestedpages
helsingborg-stad/Municipio pull request #666
Opened 2023-09-11 14:13 UTC by NiclasNorin

Not working

2023-09-11 14:13 UTC, NiclasNorin commented
Task linked: [CU-cx3c7w Gruppering av sidans huvudkategorier behöver implementeras från helsingborgs childtema.](https://app.clickup.com/t/cx3c7w)

2023-09-13 09:51 UTC, sebastianthulin requested changes

2023-09-13 09:51 UTC, sebastianthulin commented on library/Content/CustomPostType.php
> +    public function hasNestedPagesMenu() {
Dockblock

2023-09-13 10:21 UTC, NiclasNorin commented on library/Content/CustomPostType.php
> +    public function test () {
Hehe, i might have pushed this one a little too fast. Was so happy it actually worked

2023-09-13 10:30 UTC, sebastianthulin approved these changes

2023-09-13 10:30 UTC, merged