3.0/feature/gutenberg new columns block calc
helsingborg-stad/Municipio pull request #679
Opened 2023-09-20 12:45 UTC by NiclasNorin

2023-09-20 12:45 UTC, NiclasNorin commented
Task linked: [CU-865d3tkzy Kolumnval 33/67](https://app.clickup.com/t/865d3tkzy)

2023-09-25 10:29 UTC, sebastianthulin requested changes

2023-09-25 10:29 UTC, sebastianthulin commented on library/Blocks/Columns.php
>          foreach ($doc->getElementsByTagName('*') as $child) {
```suggestion
        foreach ($doc->getElementsByTagName('*') as $index =>  $child) {
```

2023-09-25 10:29 UTC, sebastianthulin commented on library/Blocks/Columns.php
> +        $index = 0;
```suggestion

```

2023-09-25 10:29 UTC, sebastianthulin commented on library/Blocks/Columns.php
>          foreach ($doc->getElementsByTagName('*') as $child) {
```suggestion
        $elements = $doc->getElementsByTagName('*'); 
        if(!empty($elements) && is_array($elements)) {
                foreach ($elements as $child) {
```

2023-09-25 10:29 UTC, sebastianthulin commented on library/Blocks/Columns.php
> +                $index++;
```suggestion

```

2023-09-25 10:29 UTC, sebastianthulin commented on library/Blocks/Columns.php
> +        }
```suggestion
                 }
            }
        }
```

2023-09-29 10:33 UTC, sebastianthulin approved these changes

2023-09-29 14:13 UTC, merged