feat: pdf generator
helsingborg-stad/Municipio pull request #767
Opened 2023-11-15 12:55 UTC by NiclasNorin

2023-11-27 09:13 UTC, NiclasNorin commented
Task linked: [CU-869301tvr PDF-generering](https://app.clickup.com/t/869301tvr)

2023-11-28 14:19 UTC, sebastianthulin requested changes

2023-11-28 14:19 UTC, sebastianthulin commented on library/Api/Pdf/CreatePdf.php
> +
General: Missing dockblocks.

2023-11-28 14:19 UTC, sebastianthulin commented on library/Api/Pdf/PdfArchiveEndpoint.php
> +use Municipio\Api\Pdf\PdfHelper;
as PDFHelper

2023-11-28 14:19 UTC, sebastianthulin commented on library/Api/Pdf/PdfArchiveEndpoint.php
> +            $pdf = new \Municipio\Api\Pdf\CreatePdf();
new PDFHelper

2023-11-28 14:19 UTC, sebastianthulin commented on library/Api/Pdf/PdfArchiveEndpoint.php
> +        foreach ($queryParams as $key => $values) {
Needs to be check if loopable.

2023-11-28 14:19 UTC, sebastianthulin commented on library/Api/Pdf/PdfArchiveEndpoint.php
> +            if (empty($values)) {
if empty 
continue; //Skips to next iteration.

2023-11-28 14:19 UTC, sebastianthulin commented on library/Api/Pdf/PdfArchiveEndpoint.php
> +        }
This may be simplified, if you use array_key_exists or simply isset.

2023-11-28 14:19 UTC, sebastianthulin commented on library/Api/Pdf/PdfArchiveEndpoint.php
> +                array_push($posts, $post);
May be removed.

2023-11-28 14:19 UTC, sebastianthulin commented on library/Api/Pdf/PdfArchiveEndpoint.php
> +        return $posts;
return $query->posts;

2023-11-28 14:19 UTC, sebastianthulin commented on library/Api/Pdf/PdfGenerator.php
> +
General: Dockblocks missing

2023-11-28 14:19 UTC, sebastianthulin commented on library/Api/Pdf/PdfGenerator.php
> +        if (!empty($replacePrintWithPdf) && $typeOfPage = $this->typeOfPage()) {
Where did $typeOfPage come from?

2023-11-28 14:19 UTC, sebastianthulin commented on library/Api/Pdf/PdfGenerator.php
> +        if (!empty($replacePrintWithPdf) && $typeOfPage = $this->typeOfPage()) {
I know this works but may be clarified.

2023-11-28 14:19 UTC, sebastianthulin commented on library/Api/Pdf/PdfHelper.php
> +        return 'https://fonts.googleapis.com/css2?family=' . urlencode($fontFamily) . ':wght@100;300;400;500;600;700;800;900&display=swap';
Not allowed to get from cloud service.

2023-11-28 14:19 UTC, sebastianthulin commented on library/Theme/Enqueue.php
> +        add_action( 'admin_enqueue_scripts', array($this, 'adminScript'), 10);
May be removed?

2023-11-28 14:19 UTC, sebastianthulin commented on library/Theme/Enqueue.php
> +    public function adminScript() {
May be removed?

2023-11-28 14:19 UTC, sebastianthulin commented on library/Helper/Image.php
> +    public static function getImageAttachmentData($id, $size = 'full') {
Why not an int?

2023-11-28 14:19 UTC, sebastianthulin commented on views/v3/partials/content/pdf/layout.blade.php
> +    <meta name="author" content="Helsingborgs stad">
Hard coded authors is not allowed.

2023-11-28 14:19 UTC, sebastianthulin commented on views/v3/partials/content/pdf/layout.blade.php
> +    @foreach($fonts as $font)
Need to check if this is loopable.

2023-11-28 14:19 UTC, sebastianthulin commented on views/v3/partials/content/pdf/layout.blade.php
> +        @if(!empty($font['google-font']))
Not allowed to connect to remote cloud platfoms.

2023-11-28 14:19 UTC, sebastianthulin commented on views/v3/partials/content/pdf/layout.blade.php
> +        @includeWhen(count($posts) > 1, 'partials.content.pdf.table-of-contents')
May consider to pass this value from controller $shouldHaveTableOfContents.

2023-11-28 14:19 UTC, sebastianthulin commented on views/v3/partials/content/pdf/style.blade.php
> +    .c-accordion .c-accordion__content[aria-hidden="false"] {
May some of these be apropriate to put in print css too?

2023-11-29 09:44 UTC, NiclasNorin commented on library/Api/Pdf/PdfArchiveEndpoint.php
> +            if (empty($values)) {
Oooo, this doesnt work in JS i believe. Will use this in the future!

2023-11-29 10:17 UTC, NiclasNorin commented on library/Helper/Image.php
> +    public static function getImageAttachmentData($id, $size = 'full') {
Removing since some cases may result in calling the function with ID being null or false

2023-12-01 13:55 UTC, sebastianthulin approved these changes

2023-12-01 13:56 UTC, merged